version: '3'

services:
  backend:
    container_name: leetcode_bot
    restart: always
    build:
      context: .
      dockerfile: ./deployment/Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:8000
      - 9229:9229
    command: npm start
