version: '3'

services:
  leetcode_bot:
    container_name: leetbot
    restart: always
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 8080:8000
      - 9229:9229
    links:
      - mongo
    command: npm start
    environment:
      - MONGO_URL
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
