version: '3'

services:
  leetcode_bot:
    container_name: leetbot
    restart: always
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 8080:8000
      - 9229:9229
    links:
      - mongo
    command: npm start
    environment:
      - TELEGRAM_TOKEN=*************************
      - MONGO_URL=mongo
      - DB_NAME=leetbot_db
      - DB_PORT=27017
      - LEETCODE_URL=https://leetcode.com/
      - SUBMISSION_COUNT=5
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - "27017:27017"
