version: '3'

services:
  leetcode_bot:
    container_name: leetbot
    restart: always
    build: docker/.
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:8000
      - 9229:9229
    command: npm start

networks:
  default:
    external:
      name: mongodb_docker_default
