version: '3'

services:
  leetcode_bot:
    container_name: leetbot
    restart: always
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:8000
      - 9229:9229
    links:
      - mongo
    command: npm start
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=leetbot_db
      - MONGODB_DATA_DIR=/data/db
