version: '3'

services:
  red:
    container_name: leetcode_bot_red
    restart: always
    build:
      context: .
      dockerfile: ./deployment/Dockerfile
    env_file:
      - .env
    image: leetcode_bot
    ports:
      - "${RED_OUT_PORT}:${PORT}"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start
    networks:
      - database_network

  prod:
    depends_on:
      - red
    container_name: leetcode_bot_prod
    restart: always
    image: leetcode_bot
    env_file:
      - .env.prod
    ports:
      - "${PROD_OUT_PORT}:${PORT}"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start
    networks:
      - database_network

networks:
  database_network:
    external:
      name: ${DATABASE_NETWORK}
