name: Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker:
    name: Test inside Container

    timeout-minutes: 10
    runs-on: ubuntu-latest

    environment: testing_environment

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: create .env file and add secrets
      run: >
        touch .env
        && echo VIZAPI_LINK=${{ secrets.VIZAPI_LINK }} >> .env

    - name: Build original image
      run: docker build -t leetcode_bot --file deployment/Dockerfile .

    - name: Build test image
      run: docker build -t leetcode_bot_test --file deployment/Dockerfile.test .

    - name: Run tests
      run: docker run --rm leetcode_bot_test
