name: Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker:
    name: Test

    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start container
      run: docker-compose -f "docker-compose.yml" up -d --build

    - name: Install Testing dependencies
      run: docker-compose run npm ci

    - name: Run tests
      run: docker-compose run npm test

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down
