name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    env:
      CI: true

    strategy:
      matrix:
        node-version: [ v16 ]

    environment: testing_environment

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      env:
        DISCORD_TEST_ENABLE: ${{ secrets.DISCORD_TEST_ENABLE }}
        DISCORD_TEST_TOKEN: ${{ secrets.DISCORD_TEST_TOKEN }} 
        TELEGRAM_TEST_ENABLE: ${{ secrets.TELEGRAM_TEST_ENABLE }}
        TELEGRAM_TEST_TOKEN: ${{ secrets.TELEGRAM_TEST_TOKEN }} 
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
